USE HR;

-- 1) HELLO, EMPLOYEES (STAGING CTE)
-- TASK: BUILD A CTE THAT RETURNS EMPLOYEE_ID, FULL_NAME, JOB_ID, DEPARTMENT_ID, SALARY.
--  OUTPUT: EMPLOYEE_ID, FULL_NAME, JOB_ID, DEPARTMENT_ID, SALARY.
--  HINT: CONCAT(COALESCE(FIRST_NAME,''),' ',LAST_NAME).

WITH CTE1 AS (
	SELECT EMPLOYEE_ID, CONCAT(COALESCE(FIRST_NAME ," ")," ",LAST_NAME) AS FULL_NAME, JOB_ID, DEPARTMENT_ID, SALARY FROM EMPLOYEES
)
SELECT FULL_NAME , JOB_ID , DEPARTMENT_ID,SALARY FROM CTE1;

-- 2) DEPARTMENT HEADCOUNT (INCLUDE 0)
-- TASK: CTE WITH EMPLOYEES GROUPED BY DEPARTMENT_ID. LEFT-JOIN TO DEPARTMENTS TO SHOW ALL DEPARTMENTS.
--  OUTPUT: DEPARTMENT_ID, DEPARTMENT_NAME, HEADCOUNT.
--  HINT: COALESCE(HEADCOUNT,0).
WITH CTE2 AS (
SELECT DEPARTMENT_ID,COUNT(*) AS HEADCOUNT FROM EMPLOYEES GROUP BY DEPARTMENT_ID
)
SELECT D.DEPARTMENT_NAME , D.DEPARTMENT_ID , COALESCE(C.HEADCOUNT,0) 
FROM DEPARTMENTS D 
LEFT JOIN CTE2 C
USING(DEPARTMENT_ID);



-- 3) AVG SALARY BY JOB
-- TASK: CTE AGGREGATES AVERAGE SALARY PER JOB_ID; JOIN TO JOBS FOR TITLES.
--  OUTPUT: JOB_ID, JOB_TITLE, EMP_COUNT, AVG_SALARY.
--  HINT: ROUND(AVG(SALARY),2).

WITH CTEA AS(
	SELECT COUNT(EMPLOYEE_ID) AS EMP_COUNT , ROUND(AVG(SALARY),2) AS AVG_SALARY,JOB_ID
    FROM EMPLOYEES
    GROUP BY JOB_ID
)
SELECT J.JOB_ID,J.JOB_TITLE,C.EMP_COUNT,C.AVG_SALARY
FROM JOBS J
JOIN CTEA C 
USING (JOB_ID);


-- 4) EMPLOYEE → MANAGER (1 HOP)
-- TASK: STAGE EMPLOYEES IN A CTE; SELF-JOIN TO GET DIRECT MANAGER NAME.
--  OUTPUT: EMPLOYEE_ID, EMPLOYEE_NAME, MANAGER_ID, MANAGER_NAME.
--  HINT: LEFT JOIN; TOP BOSS MAY HAVE MANAGER_ID = 0 OR NULL.
SELECT * FROM EMPLOYEES;
WITH CTEB AS (
	SELECT CONCAT(FIRST_NAME," ",LAST_NAME) AS MANAGER_NAME,MANAGER_ID
    FROM EMPLOYEES
    GROUP BY MANAGER_ID
)
SELECT E.EMPLOYEE_ID ,CONCAT(E.FIRST_NAME,E.LAST_NAME) AS EMPLOYEE_NAME, B.MANAGER_NAME,B.MANAGER_ID
FROM EMPLOYEES E
JOIN CTEB B
GROUP BY B.MANAGER_ID;
  


-- 5) EMPLOYEES WITHOUT A DEPARTMENT
-- TASK: USE A CTE TO LIST EMPLOYEES WHERE DEPARTMENT_ID IS NULL OR DEPARTMENT_ID=0.
--  OUTPUT: EMPLOYEE_ID, FULL_NAME, JOB_ID, DEPARTMENT_ID.
WITH CTE5 AS (
	SELECT DEPARTMENT_ID ,CONCAT(FIRST_NAME,"",LAST_NAME)AS NAAM
    FROM EMPLOYEES 
    WHERE DEPARTMENT_ID IS NULL OR DEPARTMENT_ID = 0
    GROUP BY DEPARTMENT_ID , NAAM
)
	
SELECT C.* , E.JOB_ID,E.EMPLOYEE_ID
FROM EMPLOYEES E
JOIN CTE5 C
USING (DEPARTMENT_ID);


-- 6) DEPARTMENTS WITHOUT EMPLOYEES
-- TASK: DISTINCT DEPARTMENT_ID FROM EMPLOYEES IN A CTE; ANTI-JOIN TO DEPARTMENTS.
--  OUTPUT: DEPARTMENT_ID, DEPARTMENT_NAME.

WITH CTE6 AS(
	SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES
)
SELECT D.DEPARTMENT_NAME , C.DEPARTMENT_ID 
FROM DEPARTMENTS D 
LEFT JOIN CTE6 C
ON D.DEPARTMENT_ID = C.DEPARTMENT_ID
WHERE C.DEPARTMENT_ID IS NULL;

-- 7) MAP EMPLOYEES TO REGION (CLEAN TEXT)
-- TASK: CTE JOINS EMPLOYEES → DEPARTMENTS → LOCATIONS → COUNTRIES → REGIONS AND TRIMS REGION_NAME.
--  OUTPUT: EMPLOYEE_ID, FULL_NAME, DEPARTMENT_NAME, CITY, COUNTRY_NAME, REGION_NAME.
--  HINT: TRIM(REPLACE(REGION_NAME,'\R','')).

WITH CTE7 AS (
	SELECT E.EMPLOYEE_ID , CONCAT(E.FIRST_NAME,"",E.LAST_NAME) AS FULL_NAME , D.DEPARTMENT_NAME,L.CITY,C.COUNTRY_NAME,TRIM(REPLACE(R.REGION_NAME,'\R','')) AS REGION_NAME
    FROM EMPLOYEES E
    JOIN DEPARTMENTS D
    USING(DEPARTMENT_ID)
    JOIN LOCATIONS L
    USING(LOCATION_ID)
    JOIN COUNTRIES C 
    USING(COUNTRY_ID) 
    JOIN REGIONS R 
    USING(REGION_ID)
)

SELECT EMPLOYEE_ID, FULL_NAME, DEPARTMENT_NAME, CITY, COUNTRY_NAME, REGION_NAME
FROM CTE7;


-- 8) SIMPLE PAY-BAND CHECK
-- TASK: CTE JOINS EMPLOYEES TO JOBS; RETURN ROWS WHERE SALARY < MIN_SALARY OR SALARY > MAX_SALARY.
--  OUTPUT: EMPLOYEE_ID, FULL_NAME, JOB_TITLE, SALARY, MIN_SALARY, MAX_SALARY.

WITH CTE8 AS (
	SELECT EMPLOYEE_ID ,  CONCAT(E.FIRST_NAME,"",E.LAST_NAME) AS FULL_NAME ,JOB_TITLE ,SALARY,MIN_SALARY,MAX_SALARY
    WHERE SALARY < MIN_SALARY OR SALARY > MAX_SALARY
)

SELECT EMPLOYEE_ID, FULL_NAME, JOB_TITLE, SALARY, MIN_SALARY, MAX_SALARY
FROM CTE8
GROUP BY JOB_ID;

-- 9) TOP EARNERS (OVERALL)
-- TASK: CTE SELECTING EMPLOYEE_ID, FULL_NAME, SALARY, THEN ORDER AND LIMIT TO TOP 5.
--  OUTPUT: EMPLOYEE_ID, FULL_NAME, SALARY.
--  HINT: USE THE CTE JUST TO KEEP THE FINAL SELECT CLEAN.

WITH CTE9 AS (
SELECT DISTINCT EMPLOYEE_ID ,CONCAT(FIRST_NAME,"",LAST_NAME) AS FULL_NAME,SALARY
FROM EMPLOYEES 
ORDER BY SALARY DESC
LIMIT 5
)
SELECT EMPLOYEE_ID, FULL_NAME, SALARY 
FROM CTE9;

-- using nested

with cteTemp as (
	SELECT DISTINCT EMPLOYEE_ID ,CONCAT(FIRST_NAME,"",LAST_NAME) AS FULL_NAME,SALARY
FROM EMPLOYEES 
),cteTemp2 as (
	select c.* from cteTemp c
    ORDER BY SALARY DESC
LIMIT 5
)
select employee_id,full_name,salary from cteTemp2;

-- 10) JOBS PRESENT IN EACH DEPARTMENT
-- TASK: CTE GROUPS EMPLOYEES BY DEPARTMENT_ID, JOB_ID AND COUNTS. JOIN JOBS FOR TITLE.
--  OUTPUT: DEPARTMENT_NAME, JOB_TITLE, EMPLOYEES_IN_ROLE.

WITH CTE10 AS (
    SELECT DEPARTMENT_ID, JOB_ID, COUNT(*) AS EMPLOYEES_IN_ROLE
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID, JOB_ID
)
SELECT D.DEPARTMENT_NAME,
       J.JOB_TITLE,
       C.EMPLOYEES_IN_ROLE
FROM CTE10 C
JOIN DEPARTMENTS D 
USING(DEPARTMENT_ID)
JOIN JOBS J 
USING(JOB_ID)
ORDER BY D.DEPARTMENT_NAME, J.JOB_TITLE;




-- 11) HEADCOUNT BY REGION
-- TASK: REUSE THE “MAP TO REGION” IDEA IN A CTE; THEN GROUP BY REGION.
--  OUTPUT: REGION_NAME, HEADCOUNT.
--  HINT: HANDLE NULL REGION AS “UNKNOWN”.

WITH CTE11 AS (
 SELECT COUNT(E.EMPLOYEE_ID) AS HEADCOUNT ,COALESCE(r.region_name, 'UNKNOWN') AS REGION_NAME
    FROM EMPLOYEES E
    LEFT JOIN DEPARTMENTS D
    USING(DEPARTMENT_ID)
    LEFT JOIN LOCATIONS L
    USING(LOCATION_ID)
    LEFT JOIN COUNTRIES C 
    USING(COUNTRY_ID) 
    LEFT JOIN REGIONS R 
    USING(REGION_ID)
    group by R.REGION_ID
)

SELECT  HEADCOUNT , REGION_NAME
FROM CTE11;

-- 12) COMMISSION SNAPSHOT
-- TASK: IN A CTE, COMPUTE A FLAG HAS_COMMISSION = COMMISSION_PCT > 0. THEN COUNT BY FLAG.
--  OUTPUT: HAS_COMMISSION, HEADCOUNT.
--  OPTIONAL: BREAK DOWN BY DEPARTMENT AS WELL.

WITH CTE12 AS (
SELECT COUNT(EMPLOYEE_ID) AS HEADCOUNT , 
	CASE 
		WHEN COMMISSION_PCT >0 THEN "LOW"
        WHEN COMMISSION_PCT <0 THEN "HIGH"
	END AS HAS_COMMISSION
FROM EMPLOYEES 
group by EMPLOYEE_ID
)
SELECT HEAD_COUNT,HAS_COMMISSION FROM CTE12;


-- 13) EMPLOYEES WITH ANY JOB HISTORY
-- TASK: CTE WITH DISTINCT EMPLOYEE_ID FROM JOB_HISTORY (EXCLUDE DUMMY ROW). JOIN TO EMPLOYEES.
--  OUTPUT: EMPLOYEE_ID, FULL_NAME, HISTORY_ROW_COUNT.
--  HINT: COUNT(*) OVER (PARTITION BY EMPLOYEE_ID) OR AGGREGATE BEFORE JOIN.
SELECT * FROM JOB_HISTORY;

WITH CTE13 AS (
	SELECT DISTINCT EMPLOYEE_ID ,COUNT(*) AS HISTORY_ROW_COUNT
    FROM JOB_HISTORY
    GROUP BY EMPLOYEE_ID
)

SELECT E.EMPLOYEE_ID,CONCAT(E.FIRST_NAME,"",E.LAST_NAME) AS FULL_NAME,C.HISTORY_ROW_COUNT 
FROM EMPLOYEES E
JOIN CTE13 C
USING(EMPLOYEE_ID)
WHERE E.EMPLOYEE_ID IS NOT null;

-- 14) LATEST HISTORY ROW (GENTLE)
-- TASK: CLEAN JOB_HISTORY IN A CTE (EXCLUDE ZERO/INVALID DATES) AND PICK THE LATEST ROW PER EMPLOYEE USING ROW_NUMBER.
--  OUTPUT: EMPLOYEE_ID, LAST_HIST_JOB_ID, LAST_HIST_DEPARTMENT_ID, LAST_HIST_END_DATE.
--  HINT: ORDER BY END_DATE DESC, START_DATE DESC.

WITH CTE14 AS (
SELECT E.EMPLOYEE_ID , J.JOB_ID AS LAST_HIST_JOB_ID, J.DEPARTMENT_ID AS LAST_HIST_DEPARTMENT_ID,J.END_DATE AS LAST_HIST_END_DATE
FROM EMPLOYEES E
JOIN JOB_HISTORY J 
USING(EMPLOYEE_ID)
ORDER BY END_DATE DESC, START_DATE DESC
)

SELECT EMPLOYEE_ID,LAST_HIST_JOB_ID, LAST_HIST_DEPARTMENT_ID, LAST_HIST_END_DATE
FROM CTE14;


-- 15) LOCATIONS PER COUNTRY
-- TASK: CTE GROUPS LOCATIONS BY COUNTRY_ID; JOIN TO COUNTRIES.
--  OUTPUT: COUNTRY_ID, COUNTRY_NAME, LOCATION_COUNT.
--  HINT: COALESCE(COUNTRY_NAME,'UNKNOWN').

WITH CTE15 AS (
SELECT COUNTRY_ID,COALESCE(COUNTRY_NAME,'UNKNOWN') AS COUNTRY_NAME,count(*) AS LOCATION_COUNT
FROM LOCATIONS L
JOIN COUNTRIES C 
USING(COUNTRY_ID)
group by COUNTRY_ID
)
SELECT COUNTRY_ID, COUNTRY_NAME, LOCATION_COUNT
FROM CTE15;

